### PR TITLE
Apply last example_ynh

### PR DESCRIPTION
**Pull request by yalh76**
## Problem

- *Can't be installed on bullseye*

## Solution

- *Apply last example_ynh*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by Krakinou** [comment]
Hi,
Are these changes automatically generated? There are a few strange ones (for example in the the upgrade one) .
What is the issue with bulleyes? I don't see any changes in the script that would change things for a new version?

**Comment by yalh76** [comment]
> 
> 
> Hi,
> Are these changes automatically generated? There are a few strange ones (for example in the the upgrade one) .

That's manual changes

> What is the issue with bulleyes? I don't see any changes in the script that would change things for a new version?

The issue : https://ci-apps-bullseye.yunohost.org/ci/job/477 => 
`ynh_add_systemd_config` no more has `--others_var` argument
https://github.com/YunoHost-Apps/domoticz_ynh/blob/2de62b468c34dbb73a37561eb56987029af98d56/scripts/install#L155

**Comment by yalh76** [comment]
!testme

**Comment by Krakinou** [comment]
!testme

**Review by Krakinou — APPROVED** [review]

**Pull request merged**
