### PR TITLE
Convert to v2

### PR DESCRIPTION
**Pull request by Krakinou**
- Convert to v2
- Fix domoticz version
- always provision for mqtt port

### CODE REVIEW

**Comment by Krakinou** [comment]
!testme

**Comment by Krakinou** [comment]
!testme

**Review by ericgaspar — APPROVED** [review]

**Comment by Krakinou** [comment]
!testme

**Comment by Krakinou** [comment]
!testme

**Comment by Krakinou** [comment]
!testme

**Comment by Krakinou** [comment]
!testme

**Pull request merged**
